#==============================================================================
# generate_version.ps1 - 版本信息生成脚本 / Version Info Generator
#==============================================================================
<#
.SYNOPSIS
    Generate version header file with Git and build information.

.PARAMETER OutputPath
    Path to output version_info.h file

.PARAMETER MajorVersion
    Major version number

.PARAMETER MinorVersion
    Minor version number

.PARAMETER PatchVersion
    Patch version number

.EXAMPLE
    .\generate_version.ps1
    .\generate_version.ps1 -MajorVersion 1 -MinorVersion 2 -PatchVersion 0
#>

param(
    [string]$OutputPath = "",
    [string]$MajorVersion = "1",
    [string]$MinorVersion = "0",
    [string]$PatchVersion = "0"
)

$ErrorActionPreference = "Stop"

$Script:SCRIPT_DIR = $PSScriptRoot
$Script:PROJECT_ROOT = (Get-Item "$Script:SCRIPT_DIR\..\..").FullName

# 默认输出路径 / Default output path
if (-not $OutputPath) {
    $OutputPath = Join-Path $Script:PROJECT_ROOT "Core\Inc\version_info.h"
}

#------------------------------------------------------------------------------
# 获取 Git 信息 / Get Git Information
#------------------------------------------------------------------------------
$gitCommit = ""
$gitCommitFull = ""
$gitBranch = ""
$gitTag = ""
$gitDirty = "0"

try {
    Push-Location $Script:PROJECT_ROOT
    $gitCommit = (git rev-parse --short HEAD 2>$null) -replace "`n", ""
    $gitCommitFull = (git rev-parse HEAD 2>$null) -replace "`n", ""
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null) -replace "`n", ""
    $gitTag = (git describe --tags --always 2>$null) -replace "`n", ""
    if ((git status --porcelain 2>$null)) {
        $gitDirty = "1"
    }
    Pop-Location
}
catch {
    Write-Warning "Git 信息获取失败 / Git info unavailable"
}

# 构建号 / Build number (timestamp-based)
$buildNumber = Get-Date -Format "yyMMddHHmm"
$buildDate = Get-Date -Format "yyyy-MM-dd"
$buildTime = Get-Date -Format "HH:mm:ss"
$buildTimestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"

#------------------------------------------------------------------------------
# 生成版本头文件 / Generate Version Header
#------------------------------------------------------------------------------
$versionHeader = @"
/**
 ******************************************************************************
 * @file    version_info.h
 * @brief   Auto-generated version information
 *          自动生成的版本信息
 * @note    This file is auto-generated by CI/CD pipeline. DO NOT EDIT.
 *          此文件由 CI/CD 流水线自动生成，请勿手动修改。
 ******************************************************************************
 */

#ifndef __VERSION_INFO_H
#define __VERSION_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Version Numbers / 版本号
 * ============================================================================*/
#define VERSION_MAJOR           $MajorVersion
#define VERSION_MINOR           $MinorVersion
#define VERSION_PATCH           $PatchVersion
#define VERSION_BUILD           $buildNumber

/* ============================================================================
 * Git Information / Git 信息
 * ============================================================================*/
#define GIT_COMMIT              "$gitCommit"
#define GIT_COMMIT_FULL         "$gitCommitFull"
#define GIT_BRANCH              "$gitBranch"
#define GIT_TAG                 "$gitTag"
#define GIT_DIRTY               $gitDirty

/* ============================================================================
 * Build Information / 构建信息
 * ============================================================================*/
#define BUILD_DATE              "$buildDate"
#define BUILD_TIME              "$buildTime"
#define BUILD_TIMESTAMP         "$buildTimestamp"

/* ============================================================================
 * Version Strings / 版本字符串
 * ============================================================================*/
#define VERSION_STRING          "$MajorVersion.$MinorVersion.$PatchVersion"
#define VERSION_FULL            "$MajorVersion.$MinorVersion.$PatchVersion+$buildNumber"
#define VERSION_WITH_GIT        "$MajorVersion.$MinorVersion.$PatchVersion+$buildNumber.$gitCommit"

/* ============================================================================
 * Safety Compliance / 安全合规
 * ============================================================================*/
#define SAFETY_STANDARD         "IEC 61508 SIL 2"
#define PERFORMANCE_LEVEL       "ISO 13849 PL d"
#define MISRA_COMPLIANCE        "MISRA C:2012"

/* ============================================================================
 * Macros for Runtime Access / 运行时访问宏
 * ============================================================================*/

/**
 * @brief Get version as 32-bit value
 *        获取 32 位版本值
 * @note  Format: 0xMMmmPPBB (Major.Minor.Patch.Build)
 */
#define VERSION_AS_UINT32       ((uint32_t)((VERSION_MAJOR << 24) | \
                                            (VERSION_MINOR << 16) | \
                                            (VERSION_PATCH << 8)  | \
                                            (VERSION_BUILD & 0xFF)))

/**
 * @brief Check if this is a development build
 *        检查是否为开发构建
 */
#define IS_DEV_BUILD            (GIT_DIRTY != 0)

/**
 * @brief Print version info via debug output
 *        通过调试输出打印版本信息
 */
#define PRINT_VERSION_INFO() do { \
    DEBUG_INFO("========================================"); \
    DEBUG_INFO("  TKX_ThreadX v" VERSION_STRING); \
    DEBUG_INFO("  Build: " VERSION_FULL); \
    DEBUG_INFO("  Git: " GIT_COMMIT " (" GIT_BRANCH ")"); \
    DEBUG_INFO("  Date: " BUILD_TIMESTAMP); \
    DEBUG_INFO("  Compliance: " SAFETY_STANDARD); \
    DEBUG_INFO("========================================"); \
} while(0)

#ifdef __cplusplus
}
#endif

#endif /* __VERSION_INFO_H */
"@

#------------------------------------------------------------------------------
# 写入文件 / Write File
#------------------------------------------------------------------------------
$versionHeader | Out-File -FilePath $OutputPath -Encoding UTF8 -Force

Write-Host "=========================================="
Write-Host "版本信息已生成 / Version info generated"
Write-Host "=========================================="
Write-Host "  版本 / Version: $MajorVersion.$MinorVersion.$PatchVersion"
Write-Host "  构建号 / Build: $buildNumber"
Write-Host "  Git Commit: $gitCommit"
Write-Host "  Git Branch: $gitBranch"
Write-Host "  文件 / File: $OutputPath"
Write-Host "=========================================="
